# fly.toml app configuration file generated for hydra-server on 2025-04-28T19:13:16-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hydra-server'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'performance'
  cpus = 1

[mounts]
  source = "storage"
  destination = "/data"